-
  name: varibale example
  hosts: all
  vars:
    name: Sasi
    age: 32
    gender: Male

  tasks:
    - name: Print Name
      command: echo 'My name is {{name}}'
      register: name

    - name: Print age
      command: echo 'My age is {{age}}'
      register: age

    - name: Print gender
      command: echo 'My gender is {{gender}}'
      register: gender

    - debug:
         msg: 'my name is {{name | title}}'