-
  name: using with_items
  hosts: all
  vars:
    fruits:
      - Apple
      - Banana
      - Orange
      - Grapes

  tasks:
    - name: using with_items
      command: echo "{{ item }}"
      with_items: "{{ fruits }}"

    - debug: var=hostvars[inventory_hostname]

    - debug:
        msg: "{{ item }}"
        with_items: "{{ inventory_hostname }}"