-
  name: using with_items
  hosts: all
  vars:
    fruits:
      - Apple
      - Banana
      - Orange
      - Grapes

  tasks:
    - name: using with_items
      command: echo "{{ item }}"
      with_items: "{{ fruits }}"

 #   - debug: var=hostvars[inventory_hostname]

    - name: show all the hosts matching the pattern, ie all but the group www
      debug:
      msg: "{{ item }}"
      with_inventory_hostnames:
        - all