-
  name: using with_items
  hosts: all
  vars:
    fruits:
      - Apple
      - Banana
      - Orange
      - Grapes

  gather_facts: true

  tasks:
    - name: using with_items
      command: echo "{{ item }}"
      with_items: "{{ fruits }}"

    - debug:
        msg: " {{ item }}"
        with_items: "{{ query ( 'inventory_hostname','all' )}}"