-
  name: using with_items
  hosts: all
  tasks:
    -
      name: using with_items
      command: echo "{{ item }}"
      with_items:
        - Apple
        - Orange
        - Mango
        - Banana
