-
  name: Add new line
  hosts: all
  tasks:

    - name: create a file
      command: touch /home/sjasti/Sasi.txt
      args:
        creates: /home/sjasti/Sasi.txt

    - name: get output of Sasi.txt
      shell: cat /home/sjasti/Sasi.txt
      register: output

    - debug:
        var: output.stdout_lines

    - name: add new line if doesn't exist
      shell: echo "Sasi" >> /home/sjasti/Sasi.txt
      when: output.stdout.find('Sasi_new') == -1

    - debug:
        msg: "{{ item }}"
      loop: "{{ query('inventory_hostnames', 'all') }}"