-
  name: execute a script on all nodes
  hosts: all
  user: sjasti
  become: yes
  become_user: root
  tasks:

    - name: add a line to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 10.10.10.10'

    - name: execute a script on all nodes
      script: /tmp/install_script.sh