-
  name: Add new line
  hosts: all
  tasks:

    - name: create a file
      path: '/home/sjasti/Sasi.txt'
      state: present

    - name: get output of Sasi.txt
      shell: cat /home/sjasti/Sasi.txt
      register: commnad_output

    - name: add new line if doesn't exist
      shell: echo "Sasi" >> /home/sjasti/Sasi.txt
      when: command_output.stdout.find('Sasi') == -1